language: java
sudo: true
jdk:
  - oraclejdk11

deploy:
  provider: heroku
  app: roommgmt-backend
  api_key:
    secure: d0ee007e-41f8-4d9b-83f8-467dc9f06056
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never

before_install:
  - chmod +x mvnw