language: java
sudo: true
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: senoramarillo
    token:
      secure: R91ceZ9XefdAUHQ+Ym/yBwLCFAOfBoc3oJwMjMOWUnxCM8K8rkaoJchoxpERHMKudae1jhpXbesCwSyUlBWjCcWj+zWVWj9jm4/cYY16RlTIiLHsrQ3LETEENSjfjWYXV5xXkwGJ4YJY/ckveU5VZAKD1TCgDQkeS2BI64+fvQwYhyEAxZ+sSvYIkQRuPxKdz980Z6VPVlZQiOJhaULSRWf59uTBQCdffltfN4u1PdWjkYCNx2fKhVrm3gbjB6tDben5iRaE6uAMuA/n0wpJn+Hz0K8jT5srh4MRfcJO9q+cdDq58lZS3ZGFMnZlERRNDnO4zP6xCcVWwOgSfYzc0pzo5vKCJqWSQJmoGU1eM+vNPsV24Sb/qrGq2GoVYaiKiDUoLf6cpUbba6ndPzGcLSKM4GLSbx1naN3TfWXqprK64g8IC6Cmbts+cPSyXKDGfigo6FF6cF4bsmA9PdJvQJDFrNAZj0GXu0QVxkFaH9Z4q6qo/Dm0pxdoQzrvSdKm+U8Yug/RI2CxPzUbk7Ioo0l14loGaPM0nHKA8VIGt3TsYr/b+fpc22rwcQtVn01CI4RyQSgfB72XOSPQwhviNZS+7uXua7ntyH0hn70tkJtVbaSj7DA/y00W53RHoUdVYLL/mq4FggHqcEKkHK9qPKe3xz0lhPivobM2q1pxGKA=
deploy:
  provider: heroku
  app: roommgmt-backend
  api_key:
    secure: idLdkQkQa7895KnzzlLqlb/0i/hqxvIxlCDx/nHwaKosjNS8WhJSW9y+bl24Z1GN3vFpAbVfSy9+a38rpd2xfK3xxF0iHJQmEenc+3nFtKSXxjOg/TAN+vZ4YmdTYRs5JJZSz4IAORq9Enf/6DwnNLxuqbHN6iywbh6Rreo1KddaBu85nSQpGxbdDVZDU+ZXQ3XImr14y6Mq0XfW+Ljwy6bJId9V4GIH61H7URhD0A++M1AFjcSLnCjD60zG1+v8IWNOdn2AKHcNBCrtl0IGLXcshv94ZNzHKVNsT6pxBldPUWqNNoFr/3Gj0kCpsgspvrP1kODUlGUMUDbPCItNmuMsBf/8lQUZ3SsU5NB2kaiTlL9kpiDXxFNXDz32YD1JLSUyIFJaZsu2duGwEhLfcAT/iRIOAGhcEaXQd/04kryb9334k1TupkjYUSv9iqRFD1bHj6aCJxHjB2EvqZKgvqBBqO9c5fVl02KagClr00eE427AXoIrL2LxcS03ppCc0Xi3qo25iAs8UYSq4aq/w1yadExOEgYyxU33M34nmY+J3+2ngPnjGEDr7I581JITPAbIwB2sbOD4/bs8gEvXKqDbMhs0MiWb2el/WZXZQrC2NWPyKh++MnSWTIpRly6P8+f+RaJG3JVEX98jcJzueflFpVoEUrqAv9prE9IHKY4=
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: never
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=senoramarillo_roommgmt-backend
before_install:
- chmod +x mvnw
after_success:
- bash <(curl -s https://codecov.io/bash)
