language: java
sudo: true
jdk:
  - oraclejdk11

deploy:
  provider: heroku
  api-key:
    secure: D6qiveaA4XAR0mxyDMVUVaSpsotzbE8gOyvdpQyCDOu86nbo3t4TfPmRVK34R9RF3IdneT23+8iZr2q3zYs/XzW6Cv5WpRyN1TMzGLgGK1l8s7Vj4OYFSQAhFls8gZMDc6xo8mSOcHEJ9q0b9QCAocXOs1YH/Pvq6ctvteZtHkC2IpSyyE0Vma9v5T2Q4Cqc/LiqBQM88D04PMqiwvDscdd5TgNPPhT8yMuaEhelqYB/01a8ZS3vNYnPWKRL+bShzR0TO8TYqFUQUCReH3jr/F6E3xc4thotb46mvi3nrTxrpa1RUDybNaRMyiDxeRCqeqqH7hqYV3D+/vtKZs8Bjr+1EuM5p8WyJZEZseGWmqLc5hAM4mM4J5qeI3G7ptdQDOCDwoBD+fpbIg2aUhEugIXPS2chQ3pRFTvRRl3ODtO8CCv2YaR9JgnOstKD1NrXexJKhba0wSL5VCq+BeiVIHx+bg1AVXJCKFcSHmwPyTF54t1LFcheiq9a8LOpgHQsbRZMX+S7QQcdqwd0t3H72Wk4crrW+6cUwtaLwWSBBZkYBRDxXY2vkJkK0XVH1jj3G+Gc8el1wj4vbJzOGgsZg1d+l2oIOAInCui0JQbJ1KYkHJtr25iu84QCpiVAnjxO3pVIenE9n6Vnq4m8WYvzn7WGsLNKAr8jdJ2f7nfQrzI=
  app: roommgmt-backend

before_install:
  - chmod +x mvnw