spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:file:./db/javadb
    driver-class-name: org.h2.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
server:
  port: 8088
  error:
    include-message: always