-- Add buildings
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-1, '746', 'Hauptzentrale', true);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-2, '152', 'Keynote-Halle', true);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-3, '007', 'Produktion', false);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-4, '324', 'Lager', false);

-- Add rooms
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-1, -2, '840', '5500', true);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-2, -4, '110', '400', false);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-3, -1, '972', '10', true);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-4, -3, '016', '70', false);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-5, -2, '233', '1700', true);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-6, -2, '634', '500', true);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-7, -1, '435', '7700', true);
INSERT INTO ROOM (ID, BUILDING_ID, ROOM_NUMBER, SEATS, PROJECTOR_PRESENT) VALUES (-8, -1, '133', '9900', true);