-- Add building
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-1, '746', 'Haupzentrale', true);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-2, '152', 'Kantine', true);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-3, '007', 'Produktion', false);
INSERT INTO BUILDING (ID, BUILDING_NUMBER, DESCRIPTION, PUBLIC_ACCESS) VALUES (-4, '324', 'Lager', false);